[js-formatter] Replaced old scripts with new ones.
In order to greatly simplify the scripts available for linting/formatting,
only 2 scripts left: one that performs the action to a file/list of files/all js
files in the project/module using the .jsexclude rules, and another one to be
used as a mercurial hook.

--HG--
rename : modules/org.openbravo.client.kernel/jsutils/check-dependencies => modules/org.openbravo.client.kernel/jsutils/check-npm-deps
extra : amend_source : 1d6c69223a9097b5140ae310552e165f67438237

diff --git a/modules/org.openbravo.client.kernel/jslint/jslint b/modules/org.openbravo.client.kernel/jslint/jslint
--- a/modules/org.openbravo.client.kernel/jslint/jslint
+++ b/modules/org.openbravo.client.kernel/jslint/jslint
@@ -16,12 +16,93 @@
 # * Contributor(s):  ______________________________________.
 # ************************************************************************
 
-#
-# Script used by other scripts to pass the linter to the list of js files given as arguments from the project root.
-# Note that received paths must be absolute or relative to modules/org.openbravo.client.kernel.
-#
-echo "Checking --> $@"
+SCRIPT_NAME=$(basename "$0")
+VERBOSE=false
 
-source ./modules/org.openbravo.client.kernel/jsutils/check-dependencies
+function usage() {
+  echo -n "Usage: ${SCRIPT_NAME} [-h][-v] [FILE ...]
 
-npm run jslint --prefix ./modules/org.openbravo.client.kernel -s -- "$@"
+Utility to pass the Javascript Linter to the given files, or all files from the current directory if none given.
+With no arguments, scan all files starting from the current directory taking into account .jsexclude files.
+(see jsfiles for further explanation)
+
+ Options:
+  -h                Display this help and exit
+  -v                Verbose mode. Shows additional output
+
+"
+}
+
+#
+# Execute the Linter splitting the list of files in chunks of max 250 arguments. This is done because "npm run" argument
+# size limit is much lower than the one in bash commands.
+#
+function lintFiles {
+    if [[ ${VERBOSE} == true ]]; then
+        echo "Checking the following files: $@"
+    else
+        echo "Checking $# files"
+    fi
+
+    echo "$@" | xargs --max-args 250 npm run jslint --prefix ${KERNEL_MODULE_PATH} -s || exit 1
+}
+
+#
+# Assuming the received argument is a list of files, it will check whether the paths are absolute or relative. In case
+# the path is relative, it will be converted to absolute.
+#
+function convertFiles {
+    for arg in "$@"; do
+        if [[ "${arg:0:1}" = "/" ]]; then
+            echo "${arg} "
+        else
+            echo "$(pwd)/${arg} "
+        fi
+    done
+}
+
+
+#Parse input arguments
+while getopts ":hv" arg; do
+    case ${arg} in
+        h )
+            usage
+            exit 0
+        ;;
+        v )
+            VERBOSE=true
+        ;;
+        \? )
+            echo "Invalid option: -$OPTARG" >&2
+            usage
+            exit 1
+        ;;
+    esac
+done
+shift $((OPTIND-1))
+
+KERNEL_MODULE_PATH="."
+SCAN_BASE_PATH=""
+if [[ -d "../../modules" ]]; then
+    # Running from module
+    KERNEL_MODULE_PATH="../org.openbravo.client.kernel"
+    SCAN_BASE_PATH="$(pwd)"
+elif [[ -d "./modules" ]]; then
+    # Running from Openbravo root
+    KERNEL_MODULE_PATH="./modules/org.openbravo.client.kernel"
+    SCAN_BASE_PATH="$(pwd)/modules"
+else
+    echo -e "\n\033[0;31mError:\033[0m \"$(pwd)\" is not a valid path to run the linter"
+    echo "Scan either from the Openbravo or a module root directory"
+    exit 1
+fi
+
+source ${KERNEL_MODULE_PATH}/jsutils/check-npm-deps
+
+if [[ $# > 0 ]]; then
+    files=$(convertFiles $@)
+    lintFiles ${files}
+else
+    files=$(${KERNEL_MODULE_PATH}/jsutils/jsfiles ${SCAN_BASE_PATH})
+    lintFiles ${files}
+fi
diff --git a/modules/org.openbravo.client.kernel/jslint/jslint-hg b/modules/org.openbravo.client.kernel/jslint/jslint-hg
--- a/modules/org.openbravo.client.kernel/jslint/jslint-hg
+++ b/modules/org.openbravo.client.kernel/jslint/jslint-hg
@@ -17,21 +17,38 @@
 # ************************************************************************
 
 #
-# Mercurial pretxncommit hook to check linting in modules
+# Mercurial pretxncommit hook to check linting in js code
 #
-echo "Performing lint check on modified .js resources"
+KERNEL_MODULE_PATH="."
+IS_A_MODULE=false
+if [[ -d "../../modules" ]]; then
+    # Running from module
+    KERNEL_MODULE_PATH="../org.openbravo.client.kernel"
+    IS_A_MODULE=true
+elif [[ -d "./modules" ]]; then
+    # Running from Openbravo root
+    KERNEL_MODULE_PATH="./modules/org.openbravo.client.kernel"
+else
+    echo -e "\n\033[0;31mError:\033[0m \"$(pwd)\" is not a valid path to run the linter"
+    echo "Scan either from the Openbravo or a module root directory"
+    exit 1
+fi
+
+echo "Performing jslint check on modified js resources"
+FILES=()
 for i in $(hg log -r $HG_NODE --template '{files}')
 do
-  if [[ $i == *vendor* ]]
-  then
-    echo "Skipping " $i;
-  else
-    if [ -f "$i" -a -n "$(echo $i | awk '/.js$/')" ]
-    then
-      filefullpath="$(pwd)/${i}"
-      ../org.openbravo.client.kernel/jslint/jslint-module ${filefullpath} || exit 1
-	fi
+  printf "Checking ${i}\n"
+  if [[ -f "${i}" ]]; then
+    if [[ "${IS_A_MODULE}" == true && -n "$(echo $i | awk '/.js$/')" || \
+          "${IS_A_MODULE}" == false && -n "$(echo $i | awk '/.js$/ && ! /^web/')" ]]; then
+        FILES+=("$(pwd)/${i}")
+    fi
   fi
 done
+
+if [[ -n "${FILES[*]}" ]]; then
+    ${KERNEL_MODULE_PATH}/jslint/jslint ${FILES[*]} || exit 1
+fi
 
 exit 0
diff --git a/modules/org.openbravo.client.kernel/jsutils/check-npm-deps b/modules/org.openbravo.client.kernel/jsutils/check-npm-deps
--- a/modules/org.openbravo.client.kernel/jsutils/check-npm-deps
+++ b/modules/org.openbravo.client.kernel/jsutils/check-npm-deps
@@ -1,3 +1,4 @@
+#!/bin/bash
 # *************************************************************************
 # * The contents of this file are subject to the Openbravo  Public  License
 # * Version  1.1  (the  "License"),  being   the  Mozilla   Public  License
@@ -14,40 +15,40 @@
 # * All Rights Reserved.
 # * Contributor(s):  ______________________________________.
 # ************************************************************************
-#!/bin/bash
 
 if ! [[ -x "$(command -v npm)" ]]; then
-    echo -e "\n\033[0;33mERROR:\033[0m npm command not found. Install using"
+    echo -e "\n\033[0;31mERROR:\033[0m npm command not found. Install using"
     echo -e "  sudo apt install npm\n";
     exit 1
 fi
 
+#
+# Installs eslint and prettier if not already installed
+# First argument should be the path to org.openbravo.client.kernel module
+#
 function installNodePackagesIfNeeded {
-    if [[ ! -d ./modules/org.openbravo.client.kernel/node_modules || \
-            -z "$(find ./modules/org.openbravo.client.kernel/node_modules -name eslint)" || \
-            -z "$(find ./modules/org.openbravo.client.kernel/node_modules -name prettier)" ]]; then
+    if [[ ! -d ${1}/node_modules || \
+            -z "$(find ${1}/node_modules -name eslint)" || \
+            -z "$(find ${1}/node_modules -name prettier)" ]]; then
         echo -e "eslint and/or prettier command not found. Running npm install\n"
         originalDir="$(pwd)"
-        cd modules/org.openbravo.client.kernel
+        cd "${1}"
         npm install
-        cd "$originalDir"
+        cd "${originalDir}"
     fi
 }
 
-function installNodePackagesIfNeededFromModules {
-    if [[ ! -d ../org.openbravo.client.kernel/node_modules || \
-            -z "$(find ../org.openbravo.client.kernel/node_modules -name eslint)" || \
-            -z "$(find ../org.openbravo.client.kernel/node_modules -name prettier)" ]]; then
-        echo -e "eslint and/or prettier command not found. Running npm install\n"
-        originalDir="$(pwd)"
-        cd ../org.openbravo.client.kernel
-        npm install
-        cd "$originalDir"
-    fi
-}
+echo "Checking npm and required packages are installed"
 
-if [[ -d ../../modules ]] ; then
-    installNodePackagesIfNeededFromModules
+KERNEL_MODULE_PATH="."
+if [[ -d "../../modules" ]]; then
+    KERNEL_MODULE_PATH="../org.openbravo.client.kernel"
+elif [[ -d "./modules" ]]; then
+    KERNEL_MODULE_PATH="./modules/org.openbravo.client.kernel"
 else
-    installNodePackagesIfNeeded
+    echo -e "\n\033[0;31mError:\033[0m \"$(pwd)\" is not a valid path to run the linter"
+    echo "Scan either from the Openbravo or a module root directory"
+    exit 1
 fi
+
+installNodePackagesIfNeeded ${KERNEL_MODULE_PATH}
